services:
  nginx-balancer:
    build:
      context: ./Balancer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      zbank1:
        condition: service_started
      zbank2:
        condition: service_started
      zbank3:
        condition: service_started
    restart: unless-stopped

  zbank1:
    build:
      context: ./zbank
      dockerfile: Dockerfile
    expose:
      - "8078"
    depends_on:
      zbank-postgres:
        condition: service_healthy
    restart: unless-stopped

  zbank2:
    build:
      context: ./zbank
      dockerfile: Dockerfile
    expose:
      - "8079"
    depends_on:
      zbank-postgres:
        condition: service_healthy
    restart: unless-stopped

  zbank3:
    build:
      context: ./zbank
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      zbank-postgres:
        condition: service_healthy
    restart: unless-stopped

  zbank-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: zbank
      POSTGRES_PASSWORD: zbank123
      POSTGRES_DB: zbank
    volumes:
      - ./data/db/static-postgres:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d zbank -U zbank -h zbank-postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      nginx-balancer:
        condition: service_started
    restart: unless-stopped
